version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "passw0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  web:
    image: cl-05-swarm-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:80"
    depends_on:
      - db
    command: ["dotnet", "ef", "database update"]